# Generated by Django 2.0 on 2017-12-17 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountbalance',
            options={'get_latest_by': 'date', 'verbose_name': 'balance record'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': 'date'},
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='owner',
        ),
    ]
